# This file provides instructions for packaging.

@prefix : <http://purl.org/NET/cpan-uri/terms#> .

<http://purl.org/NET/cpan-uri/dist/XML-Atom-OWL/project>
	:perl_version_from _:main ;
	:version_from _:main ;
	:readme_from _:main ;
	:test_requires "Test::More 0.61" ;
	:requires
		"Carp 1.00" ,
		"common::sense 0" ,
		"DateTime 0" ,
		"Encode 0",
		"HTTP::Link::Parser 0.100",
		"LWP::UserAgent 0",
		"MIME::Base64 0" ,
		"RDF::Trine 0.135" ,
		"Scalar::Util 0",
		"URI 1.30",
		"URI::URL 0",
		"XML::LibXML 1.70" .

_:main <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#fileName> "lib/XML/Atom/OWL.pm" .

